# Generated by Django 2.2 on 2021-03-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=10)),
                ('supplier_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=40)),
                ('cant_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=10)),
                ('customer_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('cant_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='product_inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10)),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stock_updating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('inner_quantity', models.CharField(max_length=10)),
                ('outer_quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
